### ISSUE TITLE
Zeitreihen does not work with MapProxy

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-mapproxy#25]
See:
[Test Link] (https://mf-geoadmin3.int.bgdi.ch/?dev3d=true&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false&layers_timestamp=18641231,,,&time=1864&lon=8.06010&lat=44.11429&elevation=265662&heading=359.867&pitch=-41.554)

**Comment by procrastinatio** [comment]
Ah, *jpeg*

**Comment by loicgasser** [comment]
we need to change it or you do?

**Comment by loicgasser** [comment]
see: https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/MapService.js#L986

**Comment by procrastinatio** [comment]
To me it would be logical to use `jpeg`, but native tiles are either `phgjpeg`or `png`, which is a bit confusing for the end user.

You may test it wiht `http://wmts{20-24}.(dev|int|infra).bgdi.ch`, as http://wmts22.dev.bgdi.ch/1.0.0/ch.swisstopo.zeitreihen/default/18981231/4326/12/4283/981.jpeg.

I wait before puting on prod.

**Comment by loicgasser** [comment]
Ok, I test, but where are the changes?

**Comment by loicgasser** [comment]
It works but after level 12 no more tiles...

**Comment by procrastinatio** [comment]
Hem, you should get tiles up to level 18, but tiles of levels 15, 16, 17 and 18 are all based on native tiles level 23, which is the latest available (res=2.0m)

**Comment by loicgasser** [comment]
You can test on my account until next week. It's pointing to int.

**Comment by procrastinatio** [comment]
OK, I think it is [OK](https://mf-chsdi3.dev.bgdi.ch/ltgal/shorten/68945e1fcf), but I need to clean the S3 cache.

**Comment by procrastinatio** [comment]
In fact, we have a mixture of  `Dufour` grey tiles, a seen for instance west of Feutersoy (year 1898)

`$ pngcheck ok.png`
`OK: ok.png (256x256, 8-bit grayscale, non-interlaced, 16.3%).`

`ltmom@ip-10-220-4-46:~$ pngcheck nok.png `
`OK: nok.png (256x256, 32-bit RGB+alpha, non-interlaced, 88.1%).`

I guess, these 32bits tiles have not been process through `optipng`, because `optipng`convert into 8bits greyscale image.

As mapproxy does not expect 32bits images to be greyscale, it breaks. I will patch `mapproxy`

**Comment by procrastinatio** [comment]
User the right source. Please compare
https://wmts10.geo.admin.ch/1.0.0/ch.swisstopo.zeitreihen/default/18641231/4326/13/8518/1989.jpeg (blank)

with
https://wmts20.geo.admin.ch/1.0.0/ch.swisstopo.zeitreihen/default/18641231/4326/13/8518/1989.jpeg (ok)

**Comment by loicgasser** [comment]
Thank you very much it seems to work as expected. Shall we deploy to prod?

**Comment by loicgasser** [comment]
https://github.com/geoadmin/service-mapproxy/pull/26

**Comment by procrastinatio** [comment]
@loicgasser No, I doesn't work that way....

The code from `master`of this repository is used only at the creation of a new `mapproxy`instance image, which is done not so often.

But you have to generate the `mapproxy.yaml`config and push it in appropriate directory (dev|int|infra|prod) of the `geoadmin config bucket`, and the corresponding autoscaling cluster are automagically updated.

**Comment by procrastinatio** [comment]
This one is solved
