### ISSUE TITLE
ArcGis and EPSG:2056

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/service-mapproxy#45]
Ich wollte mich hiermit nur mal wieder in Erinnerung rufen und nachfragen, ob Herr Tschanz schon Zeit hatte sich mal meine Frage anzuschauen.
In der Zwischenzeit bin ich noch auf ein anderes Problem beim WMTS (EPSG:2056) für den Layer „ch.swisstopo.pixelkarte-farbe“ gestossen.
http://wmts10.geo.admin.ch/EPSG/2056/1.0.0/WMTSCapabilities.xml

![t3](https://cloud.githubusercontent.com/assets/1236739/19591269/68143dd2-9776-11e6-9738-59a52eda900f.jpg)

Wie die beiden anderen Layer („ch.swisstopo.landeskarte-farbe-10“ und „ch.swisstopo.swissimage-product“) ist dieser eigentlich im TileMatrixSet „2056_27“ vorhanden.
Nur das beim kombinierten Layer in der letzten Zoomstufe bei mir alles durcheinander gewürfelt ankommt.

![t4](https://cloud.githubusercontent.com/assets/1236739/19591271/6d3eb0e4-9776-11e6-827e-62fc69d76a8a.jpg)

Die beiden anderen Layer weisen diesen Effekt nicht auf. Auch beim alten WMTS in LV03 (EPSG:21781) war es in Ordnung.
Könnten sie bitte prüfen woran das liegt und mir ein Feedback geben?

Vielen Dank und mit freundlichen Grüssen.

**Comment by gjn** [comment]
@procrastinatio Please treat this with high priority. It's ugly.

**Comment by procrastinatio** [comment]
1. Don't have any clue for now. It is somewhere is the rounding error, as these two projection are two close.

2. The PK10 is originally lv95. We generate lv03 tiles, and these are converted back with Mapproxy to lv95. Which is suboptimal in my view. We should generate and use lv95 tiles directly.

**Comment by procrastinatio** [comment]
I think it is fixed.
