### ISSUE TITLE
Add LV95 as Cadastral WebMap Source.

### ISSUE THREAD

**Issue by gjn** [geoadmin/service-mapproxy#62]
Apparently, cadastral Web Map WMTS only has one supported source:

https://github.com/geoadmin/service-mapproxy/blob/68ec8750075282c972c8b3296e16dbbb7fe19c48/mapproxy/templates/mapproxy.tpl#L78

It's the GeoShopt WMS in LV03.

But this WMS is now officially in LV95. So we could use the LV03 _and_ the LV95 source for the corresponding WMTS (and avoid many requests for transformation purposes).

Side note: LV03 requires transformation on the fly on the geoshop WMS - and it's slower than the LV95. Ibele will ask the geoshop to have both (LV03 and LV95) directly available.

**Comment by gjn** [comment]
After discussion with Geoshop, it's best to use LV95 as the only source.

Also, German thinks that we are doing too many requests on his server to create one tile. Can you verify that only 1 request is send per tile?

In addition, as this layer is time relevatn, I propose to _not_ cache this layer in S3. Is this possible?

**Comment by gjn** [comment]
Another thing: would it be possible to define the wmts pyramid with bigger tiles. 512x512? Or even 1024x1024? German thinks that fewer, but bitter tiles, would perform much better.

**Comment by procrastinatio** [comment]
@gjn yes, but it must have a new name, as the tile size an the resolution are essential to compute the tile address

**Comment by gjn** [comment]
Would it be hard to do this exception just for cadastralwebmap? IF too much effort, we keep the tilematixset. I let you decide.

In any case, we should change the source from lv03 to lv95 and assure 1 wms request per tile.

**Comment by procrastinatio** [comment]
@everybody please test, it has bean deployed.
